apiVersion: v1
kind: Service
metadata:
  name: {{ include "booth-module-store.fullname" . }}
  labels:
    {{- include "booth-module-store.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "booth-module-store.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
